### ISSUE TITLE
Keep updated our review about literature

### ISSUE THREAD

**Issue by hedonistrh** [hedonistrh/TurkishMusicGeneration#33]
**One-line summary (optional)**
- Add summary of different papers.

**Reason**
- I would like to keep update our review.

**Design**
- .

**Acceptance Criteria**
- .

**Outcome**
- Updated review. 👨‍🚀 

- [ ] [GANSynth](https://magenta.tensorflow.org/gansynth)

- [ ] [DeepJ](https://arxiv.org/pdf/1801.00887.pdf)

- [ ] [Anticipation-RNN](https://link.springer.com/article/10.1007/s00521-018-3868-4)

- [ ] [Music Transformer](https://magenta.tensorflow.org/music-transformer)
